[build]
  command = "npx @netlify/angular-runtime@latest build --configuration production"
  publish = "dist/clothing/browser"  # Replace with your actual `dist` folder
  functions = "netlify/functions"     # Only if using serverless functions

[build.environment]
  NODE_VERSION = "22.18.0"                 # Match your local Node version

# Disable the Angular plugin
#[[plugins]]
#  package = "netlify-plugin-one"